=== clarin-eric/clarin-resource-families/schemas/spec-corpora-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/clarin-eric/clarin-resource-families/refs/heads/main/schemas/spec-v1.schema.json",
  "title": "JSON Schema for the CLARIN Resource Families",
  "type": "object",
  "definitions": {},
  "required": [
    "Name",
    "URL",
    "Family",
    "Description",
    "Language",
    "Licence",
    "Size",
    "Annotation",
    "Infrastructure",
    "Access",
    "Publication"
  ],
  "properties": {
    "Access": {
      "$id": "#/properties/Access",
      "type": "object",
      "title": "Access information for the resource",
      "minProperties": 1
    },
 "Family": {
  "$id": "#/properties/Family",
  "anyOf": [
    {
      "type": "string",
      "enum": [
        "Academic corpora",
        "Computer-mediated communication corpora",
        "Corpora of Disordered Speech",
        "Historical corpora",
        "L2 learner corpora",
        "Legal corpora",
        "Literary corpora",
        "Manually annotated corpora",
        "Newspaper corpora",
        "Oral History corpora",
        "Parallel corpora",
        "Parliamentary corpora",
        "Reference corpora",
        "Sign language resources",
        "Spoken corpora",
        "Conceptual resources",
        "Dictionaries",
        "Glossaries",
        "Language Models",
        "Lexica",
        "Wordlists"        
      ]
    },
    {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Academic corpora",
          "Computer-mediated communication corpora",
          "Corpora of Disordered Speech",
          "Historical corpora",
          "L2 learner corpora",
          "Legal corpora",
          "Literary corpora",
          "Manually annotated corpora",
          "Newspaper corpora",
          "Oral History corpora",
          "Parallel corpora",
          "Parliamentary corpora",
          "Reference corpora",
          "Sign language resources",
          "Spoken corpora",
          "Conceptual resources",
        "Dictionaries",
        "Glossaries",
        "Language Models",
        "Lexica",
        "Wordlists"
        ]
      },
      "uniqueItems": true
    }
  ]
},

      "Description": {
      "$id": "#/properties/Description",
      "type": "string",
      "title": "Resource's description"
    },
    "Name": {
      "$id": "#/properties/Name",
      "title": "Resource name",
      "type": "string"
    },
    "URL": {
      "$id": "#/properties/URL",
      "type": "string",
      "format": "uri",
      "pattern": "^https?://",
      "title": "Link to the resource (PID preferred)",
      "examples": ["https://example.com"]
    },
    "Language": {
      "$id": "#/properties/Language",
      "type": "array",
      "title": "Languages that the tool can work with",
      "items": {
        "$id": "#/properties/languages/items",
        "type": "string",
        "title": "Language Identifier, ISO 693-3",
        "default": "eng",
        "examples": ["eng", "deu"],
        "pattern": "^(.{3})|(generic)$"
      }
     },
    "Licence": {
      "$id": "#/properties/Licence",
      "type": ["array", "string", "null"],
      "title": "Resource's licence",
      "default": null
    },
    "Size": {
      "$id": "#/properties/Size",
      "type": ["array", "string", "null"],
      "title": "Size of the resource, multiple formats possible",
      "default": null
    },
    "Annotation": {
      "$id": "#/properties/Annotation",
      "type": ["array", "string", "null"],
      "title": "Annotation layers in this resource",
      "default": null
    },
      "Infrastructure": {
      "$id": "#/properties/Infrastructure",
      "type": "string",
      "title": "which infrastructure does this item belong to"
    },
    "Publication": {
      "$id": "#/properties/Publication",
     "anyOf": [
        {
     "type": "array",
      "items": {
        "type": "string",
        "pattern": "^https?://|^$"
      },
    "uniqueItems": true
      },
{      "type": "string",
      "pattern": "^https?://|^$"
      }
      ],
      "title": "Link to a publication about the resource (PID preferred)",
      "examples": ["https://example.com"]
    }
 }
 }

=== clarin-eric/clarin-resource-families/corpora/parliamentary-corpora/icelandic-parla.json
{
      "Name": "The Icelandic Parliamentary Corpus",
      "URL": "https://clarin.is/en/resources/parliament/",
	"Family": "Parliamentary corpora",
      "Description": "This corpus contains debates in the Icelandic parliament (Al√æingi) from 1911 to 2017.\nThe corpus is available for download from CLARIN-IS (as a part of the Icelandic Gigaword Corpus) and for search through the concordancer Korp.",
      "Language": ["isl"],
      "Licence": "CC-BY 4.0",
      "Size": ["238 million tokens"],
      "Annotation": ["tokenised", "PoS-tagged", "lemmatised"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Concordancer": "https://malheildir.arnastofnun.is/?mode=rmh2018#?stats_reduce=word&isCaseInsensitive&searchBy=word&cqp=%5B%5D&lang=en&corpus=rmh2018_althingi",
	"Download": "http://www.malfong.is/index.php?lang=en&pg=&dlid=95"
	},
      "Publication": "https://www.zotero.org/groups/562080/clarin/collections/M6D8XD9Z/items/TN6TZUII/"
}

=== clarin-eric/clarin-resource-families/corpora/historical-corpora/archivo-dos-cores.json
{
      "Name": "Archivo dos AÃ§ores",
      "URL": "https://hdl.handle.net/21.11129/0000-000D-F8C0-2",
	"Family": "Historical corpora",
      "Description": "This is a reference corpus for the historical study research on the Autonomous Region of the Azores.\nThe texts are from 1878 to 1959 (first series) and 1999 to 2013 (second series).\nThe corpus is available from PORTULAN.",
      "Language": ["por"],
      "Licence": "MS NC-NoReD-ND",
      "Size": ["12 volumes of text"],
      "Annotation": [""],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "https://hdl.handle.net/21.11129/0000-000D-F8C0-2"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/reference-corpora/corpus-hedendaags-nederlands.json
{
      "Name": "Corpus Hedendaags Nederlands",
      "URL": "http://hdl.handle.net/10032/tm-a2-s8",
	"Family": "Reference corpora",
      "Description": "This is a corpus of books, blogs, newspapers, magazines and news broadcasts from the Netherlands, Flanders, Suriname and the Netherlands Antilles.\nThe corpus is available from the Dutch Language Institute.",
      "Language": ["nld"],
      "Licence": "",
      "Size": ["3 billion words"],
      "Annotation": ["PoS-tagged", "lemmatised"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Concordancer": "https://chn.ivdnt.org/"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/historical-corpora/syn-ref-fra.json
{
      "Name": "Syntactic Reference Corpus of Medieval French",
      "URL": "http://hdl.handle.net/11022/1007-0000-0000-9D2B-0",
	"Family": "Historical corpora",
      "Description": "This corpus contains texts from the 9th to the 13th century.\nThe syntactic categories of the SRCMF annotation and the grammatical principles of the annotation are explained in detail in the <a href=\"http://srcmf.org/fiches/index.html\">documentation</a>.\nThe corpus is available for download from a dedicated webpage.",
      "Language": ["fro"],
      "Licence": "CLARIN ACA",
      "Size": ["245,000 tokens"],
      "Annotation": ["tokenised", "syntactically-parsed"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "http://srcmf.org/#sec:access"
	},
      "Publication": "https://www.zotero.org/groups/562080/clarin/collections/AR3LQ524/items/4635DD6H/"
}

=== clarin-eric/clarin-resource-families/corpora/literary-corpora/anglosaxon.json
{
      "Name": "Complete Corpus of Anglo-Saxon Poetry",
      "URL": "http://hdl.handle.net/11372/LRT-867",
	"Family": "Literary corpora",
      "Description": "This corpus is available for online browsing through an external interface.",
      "Language": ["ang"],
      "Licence": "",
      "Size": [],
      "Annotation": ["none"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Browse": "https://www.sacred-texts.com/neu/ascp/"
	},
      "Publication": ""
}

=== clarin-eric/clarin-resource-families/corpora/historical-corpora/ps-corpus-es.json
{
      "Name": "PS corpus (Post-Scriptum) - ES",
      "URL": "https://hdl.handle.net/21.11129/0000-000D-F918-0",
	"Family": "Historical corpora",
      "Description": "This corpus contains informal mail letters written between the 16th and 19th centuries",
      "Language": ["spa"],
      "Licence": "CC BY-NC-ND",
      "Size": ["2,368 texts"],
      "Annotation": ["PoS tagged", "palaeographically transcribed", "modernised"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "https://hdl.handle.net/21.11129/0000-000D-F918-0"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/corpora-of-disordered-speech/plan-v-aphasia.json
{
      "Name": "Plan-V Aphasia Corpus",
      "URL": "https://planv-project.gr/",
	"Family": "Corpora of Disordered Speech",
      "Description": "This corpus contains spoken discourse data collected from Greek-speaking People with Aphasia (PWA) and from neurotypical adults.",
      "Language": ["ell"],
      "Licence": "CC BY 4.0",
      "Size": ["1.84 MB"],
      "Annotation": ["Sentence", "utterance", "clause", "POS"],
      "Infrastructure": "Other", 
      "Access": {
	"Download": "https://inventory.clarin.gr/corpus/1284"
	},
      "Publication": "https://www.zotero.org/groups/562080/clarin/collections/DVZ24JEY/items/C2YVEX3P/"
}

=== clarin-eric/clarin-resource-families/corpora/historical-corpora/histcorp.json
{
      "Name": "HistCORP - Historical Corpora",
      "URL": "https://sprakbanken-clarin.lingfil.uu.se/histcorp/",
	"Family": "Historical corpora",
      "Description": "This is a monitoring corpus for seventeen languages covering different time periods and genres.\nThe subcorpora are available under different licences; see the description on the main webpage.\nOnly some parts of the corpus are part-of-speech tagged and syntactically parsed.\nThe corpus is available for download from the Swedish Language Bank.",
      "Language": ["cop", "ces", "nld", "eng", "fra", "deu", "ell", "hun", "isl", "ita", "lat", "pol", "por", "rus", "slv", "spa", "swe"],
      "Licence": "",
      "Size": [""],
      "Annotation": ["tokenised", "PoS-tagged", "syntactically parsed"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "https://sprakbanken-clarin.lingfil.uu.se/histcorp/"
	},
      "Publication":""
}
