=== clarin-eric/clarin-resource-families/schemas/spec-corpora-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/clarin-eric/clarin-resource-families/refs/heads/main/schemas/spec-v1.schema.json",
  "title": "JSON Schema for the CLARIN Resource Families",
  "type": "object",
  "definitions": {},
  "required": [
    "Name",
    "URL",
    "Family",
    "Description",
    "Language",
    "Licence",
    "Size",
    "Annotation",
    "Infrastructure",
    "Access",
    "Publication"
  ],
  "properties": {
    "Access": {
      "$id": "#/properties/Access",
      "type": "object",
      "title": "Access information for the resource",
      "minProperties": 1
    },
 "Family": {
  "$id": "#/properties/Family",
  "anyOf": [
    {
      "type": "string",
      "enum": [
        "Academic corpora",
        "Computer-mediated communication corpora",
        "Corpora of Disordered Speech",
        "Historical corpora",
        "L2 learner corpora",
        "Legal corpora",
        "Literary corpora",
        "Manually annotated corpora",
        "Newspaper corpora",
        "Oral History corpora",
        "Parallel corpora",
        "Parliamentary corpora",
        "Reference corpora",
        "Sign language resources",
        "Spoken corpora",
        "Conceptual resources",
        "Dictionaries",
        "Glossaries",
        "Language Models",
        "Lexica",
        "Wordlists"        
      ]
    },
    {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Academic corpora",
          "Computer-mediated communication corpora",
          "Corpora of Disordered Speech",
          "Historical corpora",
          "L2 learner corpora",
          "Legal corpora",
          "Literary corpora",
          "Manually annotated corpora",
          "Newspaper corpora",
          "Oral History corpora",
          "Parallel corpora",
          "Parliamentary corpora",
          "Reference corpora",
          "Sign language resources",
          "Spoken corpora",
          "Conceptual resources",
        "Dictionaries",
        "Glossaries",
        "Language Models",
        "Lexica",
        "Wordlists"
        ]
      },
      "uniqueItems": true
    }
  ]
},

      "Description": {
      "$id": "#/properties/Description",
      "type": "string",
      "title": "Resource's description"
    },
    "Name": {
      "$id": "#/properties/Name",
      "title": "Resource name",
      "type": "string"
    },
    "URL": {
      "$id": "#/properties/URL",
      "type": "string",
      "format": "uri",
      "pattern": "^https?://",
      "title": "Link to the resource (PID preferred)",
      "examples": ["https://example.com"]
    },
    "Language": {
      "$id": "#/properties/Language",
      "type": "array",
      "title": "Languages that the tool can work with",
      "items": {
        "$id": "#/properties/languages/items",
        "type": "string",
        "title": "Language Identifier, ISO 693-3",
        "default": "eng",
        "examples": ["eng", "deu"],
        "pattern": "^(.{3})|(generic)$"
      }
     },
    "Licence": {
      "$id": "#/properties/Licence",
      "type": ["array", "string", "null"],
      "title": "Resource's licence",
      "default": null
    },
    "Size": {
      "$id": "#/properties/Size",
      "type": ["array", "string", "null"],
      "title": "Size of the resource, multiple formats possible",
      "default": null
    },
    "Annotation": {
      "$id": "#/properties/Annotation",
      "type": ["array", "string", "null"],
      "title": "Annotation layers in this resource",
      "default": null
    },
      "Infrastructure": {
      "$id": "#/properties/Infrastructure",
      "type": "string",
      "title": "which infrastructure does this item belong to"
    },
    "Publication": {
      "$id": "#/properties/Publication",
     "anyOf": [
        {
     "type": "array",
      "items": {
        "type": "string",
        "pattern": "^https?://|^$"
      },
    "uniqueItems": true
      },
{      "type": "string",
      "pattern": "^https?://|^$"
      }
      ],
      "title": "Link to a publication about the resource (PID preferred)",
      "examples": ["https://example.com"]
    }
 }
 }

=== clarin-eric/clarin-resource-families/corpora/corpora-of-disordered-speech/torgo.json
{
      "Name": "TORGO",
      "URL": "http://www.cs.toronto.edu/~complingweb/data/TORGO/torgo.html",
	"Family": "Corpora of Disordered Speech",
      "Description": "This is a corpus of dysarthric articulation and consists of aligned acoustics and measured 3D articulatory features from speakers with either cerebral palsy (CP) or amyotrophic lateral sclerosis (ALS), which are two of the most prevalent causes of speech disability, and matched controls.\nThis dataset contains 2000 samples for dysarthric males, dysarthric females, non-dysarthric males, and non-dysarthric females.",
      "Language": ["eng"],
      "Licence": "CC-BY",
      "Size": ["Originally TORGO database contains 18GB of data"],
      "Annotation": [],
      "Infrastructure": "Other", 
      "Access": {
	"Browse": "http://www.cs.toronto.edu/~complingweb/data/TORGO/torgo.html"
	},
      "Publication": "Rudzicz et al. (2012)"
}

=== clarin-eric/clarin-resource-families/corpora/cmc-corpora/feup.json
{
      "Name": "FEUP Tweets",
      "URL": "https://hdl.handle.net/21.11129/0000-000D-F8C1-1",
	"Family": "Computer-mediated communication corpora",
      "Description": "This is a corpus of tweets.\nThe corpus is available from PORTULAN.",
      "Language": ["eng"],
      "Licence": "MS NC-NoReD-ND",
      "Size": ["338 million texts"],
      "Annotation": [""],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "https://hdl.handle.net/21.11129/0000-000D-F8C1-1"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/historical-corpora/gekaapte-brieven.json
{
      "Name": "Gekaapte Brieven",
      "URL": "http://hdl.handle.net/10032/tm-a2-x3",
	"Family": "Historical corpora",
      "Description": "This is a corpus of letters and other documents from the 17th and 18th centuries.\nThese letters and documents were present on Dutch ships hijacked by the English during one of the four wars fought between Britain and the Republic of the Seven United Netherlands during this period.\nThe corpus is available from the Dutch Language Institute.",
      "Language": ["nld"],
      "Licence": "",
      "Size": [""],
      "Annotation": ["", ""],
      "Infrastructure": "CLARIN",
      "Access": {
	"Browse": "http://gekaaptebrieven.ivdnt.org/"
	},
      "Publication":""
}

=== clarin-eric/clarin-resource-families/corpora/sign-language-resources/swisssli.json
{
  "Name": "SwissSLi",
  "URL": "https://doi.org/10.48656/258r-dj15",
  "Family": "Sign language resources",
  "Description": "The <a href=\"https://www.cl.uzh.ch/en/research-groups/accessibility/resources.html\">SwissSLi</a> corpus is a unique, up to six-way multi-parallel language resource encompassing all three Swiss sign languages and their corresponding spoken languages.\nIt consists of high-quality translation data generated by deaf translators from broadcast television programs, featuring aligned sign language videos and spoken subtitles.\nThe resource supports downstream tasks including sign language machine translation, transcription, and glossing.",
  "Language": [
    "sgg",
    "ssr",
    "slf",
    "deu",
    "fra",
    "ita"
  ],
  "Licence": "CC BY-NC-SA 4.0",
  "Size": [],
  "Annotation": [
    "phrase-segmented",
    "sign-segmented",
    "sentence-segmented"
  ],
  "Infrastructure": "CLARIN",
  "Access": {
    "Download": "https://www.swissubase.ch/en/catalogue/studies/20709/19983/overview"
  },
  "Publication": "https://aclanthology.org/2024.lrec-main.1342/"
}

=== clarin-eric/clarin-resource-families/corpora/parliamentary-corpora/parlamint-ana.json
{
      "Name": "Linguistically annotated multilingual comparable corpora of parliamentary debates ParlaMint.ana 5.0",
      "URL": "http://hdl.handle.net/11356/2005",
	"Family": "Parliamentary corpora",
      "Description": "ParlaMint is a multilingual set of comparable corpora containing parliamentary debates mostly starting at the end of 2015 and extending to mid 2022.\nThe corpora have extensive metadata, most importantly on speakers (name, gender, MP and minister status, party affiliation), on their political parties and parliamentary groups (name, coalition/opposition status, Wikipedia-sourced left-to-right political orientation, and <a href=\"https://www.chesdata.eu/\">CHES</a> variables.\nThe corpus is available for download from the CLARIN.SI repository and through the noSketch Engine concordancer. Note that the version of the corpus without linguistic mark-up is available for download under a <a href=\"http://hdl.handle.net/11356/2004\">separate CLARIN.SI entry</a>.",
      "Language": ["eus", "bos", "fin", "bul", "cat", "hrv", "ces", "dan", "nld", "eng", "est", "fra", "glg", "deu", "hun", "isl", "ita", "lav", "ell", "nor", "pol", "por", "rus", "srp", "slv", "spa", "swe", "tur", "ukr"],
      "Licence": "CC BY 4.0",
      "Size": ["8,132,022 utterances", "1,231,045,523 words", "1,402,488,391 tokens"],
      "Annotation": ["tokenised", "MSD-tagged (Universal Dependencies)", "syntactically parsed (Universal Dependencies)", "named entities"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Concordancer": "https://www.clarin.si/ske/#dashboard?corpname=parlamint50_xx",
	"Download": "http://hdl.handle.net/11356/2005"
	},
      "Publication": "https://www.zotero.org/groups/562080/clarin/collections/M6D8XD9Z/items/GNY6M384/"
}

=== clarin-eric/clarin-resource-families/corpora/corpora-of-disordered-speech/rhdbank.json
{
      "Name": "RHDBank",
      "URL": "https://rhd.talkbank.org/",
	"Family": "Corpora of Disordered Speech",
      "Description": "This is a corpus of multimedia interactions for the study of communication in people with Right Hemisphere Damage (RHD).\nAccess to the data in RHDBank is password protected and restricted to members of the RHDBank consortium group.\nData in TalkBank use a consistent XML-compatible representation called CHAT. All of the data is transcribed in CHAT and CA/CHAT formats.",
      "Language": ["eng", "spa"],
      "Licence": "email request for access",
      "Size": ["30 MB transcripts", "28 GB media"],
      "Annotation": ["CHAT and CA/CHAT"],
      "Infrastructure": "CLARIN", 
      "Access": {
	"Browse": "https://sla.talkbank.org/TBB/rhd"
	},
      "Publication": ""
}

=== clarin-eric/clarin-resource-families/corpora/parliamentary-corpora/riksdag-open-data.json
{
      "Name": "Riksdag’s Open Data",
      "URL": "https://spraakbanken.gu.se/eng/resources",
	"Family": "Parliamentary corpora",
      "Description": "The corpus contains Swedish parliamentary debates from 1971 to 2016. It is annotated with <a href=\"https://spraakbanken.gu.se/swe/forskning/infrastruktur/sparv\">Sparv</a>.\nThe corpus is available for download from Språkbanken (all entries with \"Riksdag's Open Data\" in the subtitle) and through the concordancer Korp.",
      "Language": ["swe"],
      "Licence": "CC-BY",
      "Size": ["1.25 billion tokens"],
      "Annotation": ["tokenised", "lemmatised"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Concordancer": "https://spraakbanken.gu.se/korp/#?stats_reduce=word&cqp=%5B%5D&corpus=rd-bet,rd-ds,rd-eun,rd-fpm,rd-frsrdg,rd-flista,rd-ip,rd-kammakt,rd-kom,rd-mot,rd-prop,rd-prot,rd-rskr,rd-samtr,rd-skfr,rd-sou,rd-tlista,rd-utr,rd-utsk,rd-yttr,rd-ovr&lang=en",
	"Download": "http://spraakbanken.gu.se/eng/resources"
	},
      "Publication": "Borin et al. (2016)"
}

=== clarin-eric/clarin-resource-families/corpora/literary-corpora/prilit.json
{
      "Name": "The corpus of older Slovenian narrative prose PriLit 1.0",
      "URL": "http://hdl.handle.net/11356/1319",
	"Family": "Literary corpora",
      "Description": "This corpus contains texts of older Slovenian narrative prose by 12 authors.\nThe corpus is available for download from the CLARIN.SI repository.",
      "Language": ["slv"],
      "Licence": "CC BY 4.0",
      "Size": ["43 texts", "1,275,209 tokens"],
      "Annotation": ["word modernisation", "lemmatisation", "syntactic annotation (<a href=\"https://universaldependencies.org/\">Universal Dependencies</a>)"],
      "Infrastructure": "CLARIN",
      "Access": {
	"Download": "http://hdl.handle.net/11356/1319"
	},
      "Publication": ""
}
